### ISSUE TITLE
annb hangs till timeout on index.search exception

### ISSUE THREAD

**Issue by simshi** [matrixji/annb#2]
https://github.com/matrixji/annb/blob/a8dba4a4452c5004f4a8a14618299edc62d941f3/annb/runner.py#L111

- steps to reproduce
OOM in run_single_search raise from index.search

- expect
abort or print log then continue to next test

- actual happend
hang till timeout

**Comment by matrixji** [comment]
@simshi please try check with the latest version: https://pypi.org/project/annb/0.1.22/, if it's ok then we could close it.

/reopen

**Comment by simshi** [comment]
Thank you for so quick response, I'll verify it today

**Comment by simshi** [comment]
it's verified
